### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#119]
----
----
##### _**Detailed Description**_
All functionality related to managing users, roles, assignment of roles and role permissions as well as types of users.  

##### _**Inputs**_
IDIRs, 
Pre-Defined Application Roles: EXAMINER, SUPPORT, ADMIN
User Types: Novice (In-Training), Expert
Potential New Roles:  SUPERVISOR, VIEWER

##### _**Outputs**_
User Accounts with Assigned Roles and User Type
Roles and Role Permissions.

##### _**Impacts**_
Determines the access to screens and functionality with the name examination system.
This is a different method from other Registry application user setup.  Other applications require an iStore Order and is managed outside of Registries.
This new method because it is part of the application will be managed inside by registry staff.  What will this look like?

##### _**Users**_
All existing Examiners
All existing support staff
Supervisors and management (Kaine Sparks, Debbie Blyth).
We will need to determine an on-boarding process to the application.

#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Detailed Description :one:
- [x] Rough Inputs :two:
- [x] Rough Outputs :two:
- [x] Impacts :two:
- [x] Users :two::
- [x] Priority Label :one:
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application :two:
