### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#124]
----
----
##### _**Detailed Description**_
managers, supervisors, support staff need to be able to see the state of the queue as well as the ranking of specific NRs within the queue and processing statistics including turn-around-time.

#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Detailed Description :one:
- [ ] Rough Inputs :two:
- [ ] Rough Outputs :two:
- [ ] Impacts :two:
- [ ] Users :two::
- [ ] Priority Label :one:
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application :two:
----
----
