### ISSUE TITLE
Mesh Exchange Inc., BC1068555 - Alteration LTD > BEN

### ISSUE THREAD

**Issue by Sienna-Blumstengel** [bcgov/name-examination#1294]
### Home team Info
**Service Now Number:**  ?
**Staff email:** kathy.langlois@gov.bc.ca

#### What is being altered
- [x] Business type
- [ ] ~Company name - see NR info below~
- [ ] ~Name translations - see form~
- [ ] ~Resolution date: ~
- [ ] ~Share structure - see form~
- [ ] ~Remove pre-existing company conditions~

FORM: [https://app.zenhub.com/files/157936592/79217375-3bed-4bcf-9e98-a64a68eb1666/download](https://app.zenhub.com/files/157936592/79217375-3bed-4bcf-9e98-a64a68eb1666/download)

### Data from staff
**Affiliation info (Account Name or BCOL account Number):** OSLER, HOSKIN & HARCOURT LLP
**Company email (mandatory):**  vancorp@osler.com
**Company phone (optional):** n/a
**Filing date:**  December 11, 2020 at 12:30 PM
**Effective date:** same as above
**Certified By:** Registry staff

#### NR
~**Name Request Number**~
~**Phone or email used to request the name:** ~
#### Receipt info:
**Method (Routing slip or BCOL):** Routing slip? Kat didn't specify in the email, but because they provided the account name, i guess its a basic account
**BCOL Account number or routing slip #:** 713596
**BCOL DAT (if BCOL):** n/a
**Folio (optional):** n/a
**Amount:** 100.00

#### Tasks
- [ ] **BAs** to confirm that the alteration form has been filled correctly
- [ ] **BAs** to tell the devs its ready to be worked on
- [ ] **Devs** to confirm that the account can be found (SBC Account: __ )
- [ ] **Devs** to load tombstone data
- [ ] **Devs** to affiliate the entity to the account, and run the Jupyter notebook
- [ ] **Devs** complete backend work, and tell the BAs it's ready to be reviewed
- [ ] **Devs** validate that the Notice of Alteration was emailed to the company email on file
- [ ] **BAs** to confirm work has been done correctly by checking the notice of articles on bcregistry.ca/business
- [ ] **BAs** to respond to IT Ops email, and copy registries inbox (BCRegistries@gov.bc.ca), and whomever raised the ticket

**Comment by Sienna-Blumstengel** [comment]
Ahh made this in the wrong repo by accident now i can't delete itttt
