### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#137]
----
----
##### _**Detailed Description**_
A catch-all search to search for one or more name requests that satisfies  the specific need of an examiner/manager/supervisor or support staff.

##### _**Users**_
Examiners
Managers (Viewer role)
Administrators
Supervisors
Support Staff

#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Detailed Description :one:
- [ ] Rough Inputs :two:
- [ ] Rough Outputs :two:
- [ ] Impacts :two:
- [x] Users :two::
- [ ] Priority Label :one:
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application :two:
