### ISSUE TITLE
Decide

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#148]
----
----
##### _**Detailed Description**_
Upon completion of an examination ta decision is made.  It can be approved, rejected or conditionally approved.

#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Detailed Description :one:
- [ ] Rough Inputs :two:
- [ ] Rough Outputs :two:
- [ ] Impacts :two:
- [ ] Users :two::
- [ ] Priority Label :one:
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application :two:
