### ISSUE TITLE
Manage

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#177]
----
----
##### _**Detailed Description**_
Dashboards and KPIs to make management decisions about names examination.

##### _**Users**_
Supervisors
Registrar
Names Examiners

#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Detailed Description :one:
- [ ] Rough Inputs :two:
- [ ] Rough Outputs :two:
- [ ] Impacts :two:
- [ ] Users :two::
- [ ] Priority Label :one:
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application :two:
