### ISSUE TITLE
Name Request Screen Design

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#2]
##### Detailed Description
As an examiner I want to be able to see all name request information in an organized manner so that I can assess the next steps to resolve the request..
##### Epic Definition of Done (any pipleine)
- [x] Detailed Description*
- [ ] Rough Inputs*
- [ ] Rough Outputs*
- [ ] Impacts
- [ ] Users
- [ ] Priority Label
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application
----

##### Definition of Done (*-Mandatory to add to the Backlog, **-Mandatory to add to the Sprint Backlog)
- [ ] User Story*
- [ ] Priority Label*
- [ ] Story Label*
- [ ] Linked EPIC*
- [ ] Linked Scenarios**
- [ ] Inputs(Data)*
- [ ] Outputs(Data)*
- [ ] Attached Sketch/Mock-up
- [ ] User Research Test Results

----

##### Definition of Done (*-Mandatory to add to the Backlog, **-Mandatory to add to the Sprint Backlog)
- [ ] BDD Pseudo-Code**
- [ ] Estimate**
- [ ] Priority Label*
- [ ] Scenario Label*
- [ ] Assignee**
- [ ] Linked Story*

---

##### Definition of Done (*-Mandatory to add to the Backlog, **-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Complete
- [ ] Estimate
- [ ] Priority Label
- [ ] Task Label
- [ ] Assignee
- [ ] Sprint Goal (in line with the goal of the sprint)

**Comment by LJTrent** [comment]
- [ ] User Story Complete
- [ ] Linked EPIC
- [ ]  Label (Feature or Task)

**Comment by LJTrent** [comment]
###Detailed Description

**Comment by LJTrent** [comment]
###Definition of Done (To add to the Backlog)
- [ ] User Story Complete
- [ ] Linked EPIC
- [ ]  Label (Feature or Task)

**Comment by LJTrent** [comment]
###Definition of Done (Add to a Sprint)
- [ ] Acceptance Crit
- [ ] Acceptance Criteria Complete
- [ ] BDD Pseudo-Code Started
- [ ]  Estimate
- [ ]  Priority

**Comment by LJTrent** [comment]
###Acceptance Criteria Checklist (Testable)
