### ISSUE TITLE
Determine a Workplan for Defining the Remaining Examination Scenarios

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#208]
##### _**Detailed Description**_

Determine the list of remaining scenarios to define for completion of the examination screen and process including queue management.

##### _**Sprint Goal**_
Support planning for subsequent sprints.

##### _**Acceptance Criteria**_
-tasks defined  and assigned
-entered into zenHub

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [x] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [x] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
Work plan has been created to do the research to build the scenarios for:

Examine
the example system behavior
put an NR onhold (106, 125)
theasurus structure-adding terms - senior examiner, manager only -approval process
dictionary definition  (tool tips bubble - hOver over the word), pcik a dictionary
Name Request history
final reservation-reservation count-linked toether in nro-(153
Add Comment (internal)
trademark inclusion-ftp or screen scrape-define what we need in a task for dev.
consents - upload

Decide
Approve, Conditionally Approve/Consent
Reject
cancellaton of NR-payment integration
Add Comment
