### ISSUE TITLE
Client framework for SPA

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#224]
#### **Task** (Use for Work not Directly related to a Story but supports the Sprint Goals)
Load Client framework for SPA

##### _**Detailed Description**_
Loaded a small 'hello world' class SPA written in JavaScript using
* Vue  <- JS Micro-framework
* Vuex <- client data store sync
* Vue-Router <- HTML5 compliant routing for SPA
* axios <- promise based XHR
* Vuelidate <- form field validation

**Temporary** Added a  *settings* page that holds a URL and SecurityKey that allows Firebase to be used as a back end, while the real back end is getting build.

**Temporary** Added login/signup/logout pages and actions that uses the Firebase info until the KeyCloak environment can replace it.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----
----
----
#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Detailed Description :one:
- [ ] Rough Inputs :two:
- [ ] Rough Outputs :two:
- [ ] Impacts :two:
- [ ] Users :two::
- [ ] Priority Label :one:
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application :two:
----
----
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] User Story :one:
- [ ] Priority Label :one:
- [ ] Story Label :one:
- [ ] Linked EPIC :two:
- [ ] Linked Scenarios :two:
- [ ] Inputs(Data) :one:
- [ ] Outputs(Data) :one:
- [ ] Attached Sketch/Mock-up
- [ ] User Research Test Results
----
----
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] BDD Pseudo-Code :two:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Scenario Label :one:
- [ ] Assignee :one:
- [ ] Linked Story :one:
----
----
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----
