### ISSUE TITLE
Determine Data Recovery Requirements

### ISSUE THREAD

**Issue by VarekBoettcher** [bcgov/name-examination#226]
----
#### **Task** (Use for Work not Directly related to a Story but supports the Sprint Goals)
Determine policies and/or legislation that create data recovery requirements this project is obligated to meet.  Clearly delineate "nice to have" from "required by legislation".

##### _**Sprint Goal**_
Recovery requirements drive retention implementation.  Ensures the new application meets legislative and policy requirements for data retention.

##### _**Acceptance Criteria**_
- [] Data recovery requirements identified.
- [] Data recovery "nice to have"s identified.
- [] Requirements and "nice to have"s documented and placed on SharePoint.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----

**Comment by JohnamLane** [comment]
ORCS comes into play for electronic records. I am working to determine what our rules are for that.

**Comment by JohnamLane** [comment]
I will update this ticket once I hear back about ORCS, but then it will need to get revised as more is learned about how the new app will store data. Suggest we remove this from sprints and that it live on as a background task for me.

**Comment by LJTrent** [comment]
@knmurray This should be part of the deployment plan so I re-assigned to you.

**Comment by LJTrent** [comment]
Covered by database back-up and recovery.
