### ISSUE TITLE
Vue Keycloak Api Minimal Test Client

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#428]
#### **Task**
Create a minimal Vue client that can be used to test the vue.js keycloak, api calls to test on all services and CORS issues.

##### _**Detailed Description**_
Create a minimal Vue client that can be used to test the vue.js keycloak, api calls to test on all services and CORS issues.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----
