### ISSUE TITLE
SOLR: Add support for multiple cores

### ISSUE THREAD

**Issue by VarekBoettcher** [bcgov/name-examination#429]
----
#### **Task** (Use for Work not Directly related to a Story but supports the Sprint Goals)
Alter SOLR container to support pulling a comma separated list of cores from build environment and pre-build them.

#####  _**Detailed Description**_
The current SOLR container invocation scripts only know how to pull a single core name from the environment.  Add ability to invocation script to loop through a list of cores that would be injected during the deploy.

First script to alter is in openshift-solr/s2i/bin/run.

##### _**Acceptance Criteria**_
- [ ] SOLR container creates and starts with multiple core names.
- [ ] Core names on the CORE_NAME value in the namex-api/solr/openshift/deploy.param file.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [ ] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@VarekBoettcher  This is fine. You dont have to rename it.
