### ISSUE TITLE
Private Repo & Private base image for NR Sync Oracle Libraries

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#430]
#### **Task** 
Private Repo & Private base image for NR Sync Oracle Libraries
##### _**Detailed Description**_
Oracle client libraries require consent of license to use, which means they can not be stored in our public GitHub repo as this would contravene the license.

Until the CSI/DevOps has something like Artifactory in place to manage private RPMs and other binaries, we will create a private repo for the Oracle RPMs, and a private Image to the build the client from.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----
