### ISSUE TITLE
Python test-jig and API - SOLR

### ISSUE THREAD

**Issue by VarekBoettcher** [bcgov/name-examination#433]
----
#### **Task** (Use for Work not Directly related to a Story but supports the Sprint Goals)

Create a python back-end app that uses the SOLR access libraries to connect to our SOLR instance.

##### _**Detailed Description**_

The application will be used as a test-jig and a template for connecting to SOLR from the API code.

##### _**Acceptance Criteria**_
- [ ] Project creates a container that interfaces to the SOLR instance

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [x] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
