### ISSUE TITLE
Custom docker image and add database drivers - SOLR

### ISSUE THREAD

**Issue by VarekBoettcher** [bcgov/name-examination#438]
----
#### **Task** (Use for Work not Directly related to a Story but supports the Sprint Goals)

Alter SOLR container to add additional application directories and drivers.

##### _**Acceptance Criteria**_
- [x] Create new repo
- [ ] Alter Docker build file
- [ ] Add image to namex image stream
- [ ] Build SOLR from new image

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [x] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
