### ISSUE TITLE
Edit NR - complete functionality

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#591]
#### **Task**
- [ ] get/ensure NR put/post is working to save NR details upon save
- [x] expiry and consumption date - display but not not editable KIAL
- [ ] additional info - built from transactions? check spreadsheet/screenshot from Lorna
  - not editable 
- [ ] corp # - with backend validation against corp db KIAL
- [ ] previous NR - with backend validation against NR db - DO NOT DO 
- [x] submitted count - display but not editable KIAL

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by katiemcgoff** [comment]
[edit-nr-details-info.txt](https://github.com/bcgov/name-examination/files/2165531/edit-nr-details-info.txt)

**Comment by katiemcgoff** [comment]
[Issue 101 Edit Name Request Details - Requirements.docx](https://github.com/bcgov/name-examination/files/2191765/Issue.101.Edit.Name.Request.Details.-.Requirements.docx)
