### ISSUE TITLE
URL for linking to specific NR

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#672]
#### **Task** 
To be used in NR Details, History details, and maybe Conflicts details.
Something like
https://namex-test.pathfinder.gov.bc.ca/nameExamination/NR%201234567 
or 
https://namex-test.pathfinder.gov.bc.ca/nameExamination/NR/NR%201234567

##### _**Acceptance Criteria**_

When user clicks the link, they are taken to the details of an exact NR. Just like if they loaded it from the header search or from the regular Search screen.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two days:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
This is being addressed in a different way in the new UI for conflicts. Generally examiners dont care about name history as much. SO we are not spending time on it.
