### ISSUE TITLE
Requestor interviews

### ISSUE THREAD

**Issue by megwhetung** [bcgov/name-examination#89]
#### **Task** (Use for Work not Directly related to a Story but supports the Sprint Goals)

Interview people who have recently been through the process of requesting a name, to understand challenges and opportunities for improvements to the staff process that will also offer value to people requesting names**_

##### _**Sprint Goal**_
To get some citizen feedback as part of the user research.

##### _**Acceptance Criteria**_
- complete one interview that is already scheduled (March 7)
- recruit two more interview participants and schedule sessions with them

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [x] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [x] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
We have decided not to do any more foundational interviews as we have enough information and need to focus on deliverables and specific questions to deliver the app.
