### ISSUE TITLE
Examine

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#97]
##### _**Detailed Description**_
All of the steps necessary to review and examine and make a decision about a names request.

##### _**Inputs**_
Name Request submissions from NRO.
Existing Name Requests before and during examination and after a decision has been made.

##### _**Outputs**_
Approved Examination
Rejected Examination
Conditionally approved examination.

##### _**Impacts**_
-The core of the application.  
-Notifications sent to the client
- Name request results impact SOFI, COLIN,  SONIA, REGI, ONESTOP

##### _**Users**_
Examiners

#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Detailed Description :one:
- [x] Rough Inputs :two:
- [x] Rough Outputs :two:
- [x] Impacts :two:
- [x] Users :two::
- [x] Priority Label :one:
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application :two:
